### ISSUE TITLE
node:5.6-slim is unsupported

### ISSUE THREAD

**Issue by tianon** [mongo-express/mongo-express-docker#1]
See https://github.com/nodejs/LTS for information about Node's support levels, but `5.6-slim` is no longer supported.

The two main options I see are to switch to either `node:5-slim` (latest in the 5.x series, staying supported, but at the cost of a slightly more experimental Node release that won't be supported for a ton longer, but maybe punt on that until 6.x is officially LTS?) or actually downgrading to the current LTS, `node:4-slim`, but I don't know the implications of downgrading (do users of the image commonly enhance it by installing more utilities?  does it work better on 5.x?)

**Comment by knickers** [comment]
I don't expect that the users commonly install utilities, but that is just an assumption. I'm all for upping node to the latest in version 5, I'll build it and see how it does.

This might also be applicable to users who install directly using the main https://github.com/mongo-express/mongo-express repo.

**Comment by knickers** [comment]
mongo-express seems to run well in `node:5-slim` (which is v5.11.1 right now).

Do you have any thoughts @wulfsolter?

**Comment by knickers** [comment]
Updated to `node:5-slim` here: 8307e91473be1b6849e89acc4d347eec0116293a
