### ISSUE TITLE
wait for db port to be available

### ISSUE THREAD

**Issue by thomasleveil** [mongo-express/mongo-express-docker#11]
When starting a mongo-express container, with environment variable `ME_CONFIG_MONGODB_SERVER` set, at the same time as a mongo container, mongo-express eventually fails to start due to failing to connect to mongo.

It would be nice if the mongo-express container could wait retry a few times in such case before eventually failing after a timeout.

---

```
mongoexpress_1   | Welcome to mongo-express
mongoexpress_1   | ------------------------
mongoexpress_1   |
mongoexpress_1   |
mongoexpress_1   | Mongo Express server listening at http://0.0.0.0:8081
mongoexpress_1   | Server is open to allow connections from anyone (0.0.0.0)
mongoexpress_1   | basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
mongoexpress_1   |
mongoexpress_1   | /node_modules/mongodb/lib/server.js:265
mongoexpress_1   |         process.nextTick(function() { throw err; })
mongoexpress_1   |                                       ^
mongoexpress_1   | MongoError: failed to connect to server [db:27017] on first connect
mongoexpress_1   |     at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35)
mongoexpress_1   |     at emitOne (events.js:116:13)
mongoexpress_1   |     at Pool.emit (events.js:211:7)
mongoexpress_1   |     at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12)
mongoexpress_1   |     at Object.onceWrapper (events.js:317:30)
mongoexpress_1   |     at emitTwo (events.js:126:13)
mongoexpress_1   |     at Connection.emit (events.js:214:7)
mongoexpress_1   |     at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49)
mongoexpress_1   |     at Object.onceWrapper (events.js:315:30)
mongoexpress_1   |     at emitOne (events.js:116:13)
mv-rapport-commun-recette_mongoexpress_1 exited with code 1
```

**Comment by tianon** [comment]
Looks like https://github.com/mongo-express/mongo-express/issues/342 is the relevant issue upstream -- IMO, it makes more sense to implement this wait/retry behavior in Mongo Express itself.

**Comment by thomasleveil** [comment]
However, it is straightforward to implement here while it looks quite error prone to implement on the mongo-express project. This is due to the fact that in the mongo-express project, you can connect to multiple mongo instances, replicasets, etc ; while on this project only use the single connection use case.
Issue  mongo-express/mongo-express#342 is sitting unresolved for over a year now :/
