### ISSUE TITLE
Push latest release to Docker hub?

### ISSUE THREAD

**Issue by Remco75** [mongo-express/mongo-express-docker#16]
I filed this issue on the main repo: https://github.com/mongo-express/mongo-express/issues/431

But it appears that the latest release supporting the readonly flag is not in the docker hub yet.

Could someone update the hub?

**Comment by tianon** [comment]
Whoops, I dropped the ball on this one (after https://github.com/mongo-express/mongo-express-docker/pull/14), sorry!  I'll make a PR to https://github.com/docker-library/official-images momentarily!

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/4653 :+1:

**Comment by Remco75** [comment]
Thnx ! gonna try tomorrow, will close issues if it works 👍👍

**Comment by Remco75** [comment]
Work like a charm, will close this one!
