### ISSUE TITLE
can't name mongo anything else but 'mongo'

### ISSUE THREAD

**Issue by thomasd3** [mongo-express/mongo-express-docker#20]
in docker-compose.yml:

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=I_can_put_anything_here

this will work, as long as the mongo container is named 'mongo'; the ME_CONFIG_MONGODB_SERVER field is totally ignored.

if I name my mongo container 'mongodb', then mongo-express doesn't start properly.

**Comment by tianon** [comment]
I can't seem to reproduce a failure:

```console
$ docker run -dit --name some-mongo mongo
3aac2c3ea199302ee35c16bcd8318f606ba25e431e7a0f91a07fb81fe3918a31

$ docker run -it --rm --link some-mongo -e ME_CONFIG_MONGODB_SERVER=some-mongo -p 8081:8081 mongo-express
Waiting for some-mongo:27017...
Welcome to mongo-express
------------------------


Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)
basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
Database connected
Admin Database connected
```

(Then hitting http://localhost:8081 in my browser pulls up the interface appropriately, as expected.)

**Comment by thomasd3** [comment]
I found the problem:
I have everything on a nginx reverse proxy subnet and I needed to export the containers BOTH on that network but also locally.
