### ISSUE TITLE
Add support for replica set

### ISSUE THREAD

**Issue by dprslt** [mongo-express/mongo-express-docker#21]
When using a mongo replicaset, the dockerfile wait for TCP port on the full chain.

Config :
`ME_CONFIG_MONGODB_SERVER="mongo-0.mongo,mongo-1.mongo"`

While booting, the container logs some errors while waiting for hosts 

```
Tue Oct  9 08:41:51 UTC 2018 retrying to connect to mongo-0.mongo,mongo-1.mongo:27017 (2/5)
/docker-entrypoint.sh: line 14: mongo-0.mongo,mongo-1.mongo: Name does not resolve
/docker-entrypoint.sh: line 14: /dev/tcp/mongo-0.mongo,mongo-1.mongo/27017: Invalid argument
```

**Comment by tianon** [comment]
Interesting -- IMO it probably makes sense to just skip the "TCP wait" behavior completely if `ME_CONFIG_MONGODB_SERVER` contains a comma.

What do you think, @knickers?

**Comment by dorsanyvision** [comment]
We have several mongo containers in replica set mode and each one of them is using different port
for example:
```mongodb1:27017
mongodb2:27018
mongodb3:27019```

Please also add support to multiple ports to each mongo container

**Comment by pavelgronsky** [comment]
Please explain me how I can used different host with different port in mongo-express by docker-compose?

This my docker-compose config:

` mongo_express:
        image: mongo-express
        container_name: MongoExpress
        restart: always
        ports: 
            - "8081:8081"
        environment:
              ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
              ME_CONFIG_MONGODB_SERVER:  mongo2,  mongo1
              ME_CONFIG_OPTIONS_EDITORTHEME: 'darcula'
        links:
           - 'mongo1'
           - 'mongo2'
`

Where 
mongo:27018
mongo:27019

I take the same error.
