### ISSUE TITLE
Allow usage without docker linking

### ISSUE THREAD

**Issue by SkeLLLa** [mongo-express/mongo-express-docker#23]
Now if mongo is not linked to docker, but is available via host/port mongo express will restart.

The "port check" is not valid:
```
/dev/tcp/$host/$port
```
Also after restart it 

That makes this image only usable with docker compose and absolutely useless for using for other environments when mongo is located on different machine.

Expected behaviour:
Allow setting `ME_CONFIG_MONGODB_SERVER` to something other than linked host
Server should connect server set in `ME_CONFIG_MONGODB_SERVER` variable if it's runnning on local docker or remote machine

**Comment by tianon** [comment]
https://github.com/mongo-express/mongo-express-docker/blob/b089fe7708d9dd619d648a6ec226fe0175b27740/docker-entrypoint.sh#L22-L24

This looks right to me :confused:

**Comment by tianon** [comment]
It even seems to work fine here without using `--link`:

```console
$ docker pull mongo:4.0
4.0: Pulling from library/mongo
Digest: sha256:c4e8225e68348b18283cf5c523f99122426fe1e15d883104e24c61bedb4b2ca7
Status: Image is up to date for mongo:4.0

$ docker pull mongo-express
Using default tag: latest
latest: Pulling from library/mongo-express
Digest: sha256:e476e1786f51729cf306e9602798a0f0fc74804060e4643724ef0c161438d2e8
Status: Image is up to date for mongo-express:latest

$ docker network create test
2c355950877b799066855b3654634e9a884543da2e94e5dba7bf3b1b8724e6dd

$ docker run -dit --name test-mongo --network test mongo:4.0
a22da3753caefc43493ce2168721a50459c62cca3bf4f720d5ae587aabc4663f

$ docker logs test-mongo | grep 'waiting for connections'
2018-11-01T19:56:49.895+0000 I NETWORK  [initandlisten] waiting for connections on port 27017

$ docker run -it --rm -p 8081:8081 -e ME_CONFIG_MONGODB_SERVER=test-mongo --network test mongo-express
Waiting for test-mongo:27017...
Welcome to mongo-express
------------------------


Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)
basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
Database connected
Admin Database connected
```

I can also hit http://127.0.0.1:8081 in my browser and pull up the mongo-express interface to modify things successfully. :confused:

**Comment by SkeLLLa** [comment]
@tianon the point is to run mongo server on different instance and without docker network.

Also with docker compose `depends_on` this check is not necessary.

**Comment by tianon** [comment]
So, those two things are different so I'll respond to each separately:

1. > with docker compose depends_on this check is not necessary.

    While this is true for `docker-compose`, this is _not_ at all true for Docker Swarm Mode / `docker stack deploy` -- `depends_on` is entirely ignored there.

2. > the point is to run mongo server on different instance and without docker network.

    Ok, that should work fine too -- in that case, you'd expose `mongo` externally on the second instance and point `ME_CONFIG_MONGODB_SERVER` to the IP address of it.  I'm still not understanding the issue you're facing?  Can you provide some simple steps to reproduce the issue more directly?

**Comment by tianon** [comment]
Here's that same test above again, this time without a Docker network (and performed on two hosts):

```console
$ ip --brief -4 address show dev lan0
lan0             UP             172.29.0.94/16 

$ docker run -dit -p 27017:27017 --name test mongo:4.0
ca9c005365754f49c8040fa4720610ee1de5fd72cce52146d4d5cd088e8b5c82

$ docker logs test | grep 'waiting for connections'
2018-11-01T21:01:58.744+0000 I NETWORK  [initandlisten] waiting for connections on port 27017

$ # now on second server:
$ ip --brief -4 address show dev lan0
lan0             UP             172.29.0.230/16 

$ docker run -it --rm -p 8081:8081 -e ME_CONFIG_MONGODB_SERVER=172.29.0.94 mongo-express
Waiting for 172.29.0.94:27017...
Welcome to mongo-express
------------------------


Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)
basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
Database connected
Admin Database connected
```

**Comment by SkeLLLa** [comment]
Thanks. I've already created an image that works on my env.
