### ISSUE TITLE
Update to version 0.52.1

### ISSUE THREAD

**Issue by gabrieligbastos** [mongo-express/mongo-express-docker#29]
Hello, @tianon @knickers!

I'd like to reach out to you and ask if you can please update the project to the 0.52.1 version, as it adds a new feature to support secrets on docker with _FILE suffix

Thanks!

**Comment by ErikAbele** [comment]
Yes, that would be awesome – the [official image](https://github.com/docker-library/official-images/blob/master/library/mongo-express) is quite dated (0.49.0 from 2018-08-24).

Thank you!

**Comment by gabrieligbastos** [comment]
any plans?

**Comment by ErikAbele** [comment]
Awesome, thank you for taking this on!

**Comment by NeverMine17** [comment]
Any updates on this issue?

**Comment by maszaa** [comment]
Build based on the current Dockerfile is broken as it uses version 0.51.0 of Mongo-Express which has the issue  where selecting document in collection view for editing doesn't work.

**Comment by vincentsijben** [comment]
any update on this?

**Comment by shadowbane1000** [comment]
0.54 would be nice... :)  I need the bindata 3&4 as ID support.

**Comment by tianon** [comment]
See https://github.com/mongo-express/mongo-express-docker/commit/4b43fe8a1206434cb32a006cd155dd71462f092f and https://github.com/docker-library/official-images/pull/7394 :tada: :+1:
