### ISSUE TITLE
Could not create collection

### ISSUE THREAD

**Issue by yeesuu** [mongo-express/mongo-express-docker#37]
```iml
mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 111111
    volumes:
      - ./../mongodb:/var/lib/mongodb
  mongo-express:
    image: mongo-express:0.49
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 111111
    links:
      - mongo
```
<img width="863" alt="111" src="https://user-images.githubusercontent.com/6366499/64524003-35710100-d330-11e9-8f07-fb9df9daaba0.png">

**Comment by baturorkun** [comment]
> I have the same issue.

could you solve it?

**Comment by ernestohs** [comment]
@baturorkun Yes, I removed the versions, and for `mongo-express` and added mode variables `ME_CONFIG_MONGODB_AUTH_*` using the correct user/password that makes the configuration execute properly.

**Comment by BlackthornYugen** [comment]
Sounds like this was resolved.
