### ISSUE TITLE
Basic login security

### ISSUE THREAD

**Issue by tim-rohrer** [mongo-express/mongo-express-docker#44]
I'm confused on how to configure this for even basic website authentication.

I have tried multiple configuration options in my `docker-compose.yml` but only got the login prompt one time. I didn't tell Safari to save it, yet I haven't not had it come back. 

What specifically do I need to configure to make it so I get a login prompt for `mongo-express`.

Thank you.

```
version: '3.6'

services:

  mongo:
    container_name: mongo
    build: .
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MDB_ADMIN
      MONGO_INITDB_ROOT_PASSWORD: $MDB_PWD
    volumes:
      - ./data:/data/db
    networks:
      - my-bridge-net

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8008:8081
    env_file: .env
    environment:
#      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
#      ME_CONFIG_MONGODB_ENABLE_ADMIN: 0
      ME_CONFIG_BASICAUTH_USERNAME: username
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MDB_ADMIN
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MDB_PWD
    networks:
      - my-bridge-net

networks:
  my-bridge-net:
    external: true```

**Comment by BlackthornYugen** [comment]
Your config looks correct for basic auth. Can you test it with the latest image?

**Comment by tim-rohrer** [comment]
Apologies, but probably not. I don't think I even have the compose file any more. I use Compass with my MongoDB databases.

I will close this for record keeping.
