### ISSUE TITLE
Accessing documents with BinData as value for `_id`

### ISSUE THREAD

**Issue by riker09** [mongo-express/mongo-express-docker#5]
Hello there. I'm new to MongoDB and C#, so please don't frown when this is a stupid question. But I'm unable to access documents in the web client where the value for the `_id` column (property?) was generated from a C# `Guid`.

Here's my (simplified) C# class:

```csharp
    public class MyClass
    {
        [BsonId]
        public Guid MyId {get; set; }

        public string MyPropertyA { get; set; }
    }
```

Now when I store a document:

```csharp
var myClassObj = new MyClass
{
    MyId = Guid.NewGuid(), // Let's assume it is "C56A4180-65AA-42EC-A945-5FD21DEC0538"
    MyPropertyA = "Foo"
}
await mongoClient.SaveDocument(myClassObj.ToBsonDocument());
```

This is what ends up in the mongo database (retrieved with mongo cli):
```javascript
{ "_id" : BinData(3,"gEFqxapl7EKpRV/SHewFOA=="), "MyPropertyA": "Foo" }
```

This is what is rendered in the collection view:

![mongodb guid error](https://user-images.githubusercontent.com/568497/30693054-3512ab8e-9ece-11e7-9ad9-bc4aa78304ac.PNG)

And I cannot open the document. The error message is `Document not found!`.

I'm not sure if this is an error with mongo, mongo-express or C# Guids. I'm still learning and would appreciate some insights.

**Comment by knickers** [comment]
Thanks @riker09! Unfortunately this repo is only for the docker build of
mongo-express, main development happens over in the
https://github.com/mongo-express/mongo-express repo. Will you please repost
your issue there?

**Comment by riker09** [comment]
Done.
