### ISSUE TITLE
[Bug] Basic auth don't work behind traefik (keep repeating asking log/pwd)

### ISSUE THREAD

**Issue by Yivan** [mongo-express/mongo-express-docker#50]
Hello,

We use traefik v2 as frontal reverse proxy.
It seems the auth basic feature of mongo express docker don't work with traefik.
When we set `ME_CONFIG_BASICAUTH_USERNAME` and `ME_CONFIG_BASICAUTH_PASSWORD`, on the browser there is the popin asking for login/password, but even with good credential, it keeps again and indefinitly to ask them.

For information, on this same docker stack we use apache behing traefik and the basic auth of apache works fine, that's why I suspect mongo-express-docker to have maybe a problem.

Thanks.

**Comment by rizerzero** [comment]
Basic auth works for me with traefik 2.1
 ```
  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.mongo-express.rule=Host(`${URL}`)
      - traefik.http.routers.mongo-express.entrypoints=web-secured
      - traefik.http.routers.mongo-express.tls=true
      - traefik.http.routers.frontend.service=mongo-express
      - traefik.http.routers.mongo-express.tls.certresolver=le
      - traefik.http.services.mongo-express.loadbalancer.server.port=8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME : "ambiance"
      ME_CONFIG_MONGODB_SERVER : "mongodb"
      ME_CONFIG_BASICAUTH_USERNAME : "**********"
      ME_CONFIG_BASICAUTH_PASSWORD : "***********"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "***********"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "***********"
    networks:
      - backend
      - proxy
   ```

**Comment by Yivan** [comment]
I close this issue to clean github, because it seems it was a side effect in our setup, and all is working fine now.
Thanks.
