### ISSUE TITLE
Actualize docker image.

### ISSUE THREAD

**Issue by bdod** [mongo-express/mongo-express-docker#6]
Please actualize your official docker image on https://hub.docker.com/_/mongo-express/.

Some issues which was already fixed in main branch at github , still exists in image on docker hub.

for example: issue #361 (db is not a function) still exist at this image.

PS: I'm have alredy fixed this local, but think it will be a good practice update official image . Thanks

**Comment by knickers** [comment]
Thank you for the kick-in-the-pants. Been dealing with some personal issues
and slacking on updates. I'll work on this as soon as I can.

**Comment by Codelica** [comment]
Just a heads up that the image is at v0.45 which has some open issues that have been fixed, like https://github.com/mongo-express/mongo-express/issues/394

Thanks!

**Comment by bdod** [comment]
Great ! Thanks :)

**Comment by cotofei78** [comment]
Hello! Please update docker image to 0.47.
It has several fixes, like https://github.com/mongo-express/mongo-express/pull/406

Thanks!
