### ISSUE TITLE
Mongo Express Docker Container not activating.

### ISSUE THREAD

**Issue by SAIMMINHAS** [mongo-express/mongo-express-docker#68]
Hi,

I am trying to check the Status of a newly created Mongo Express Docker Container by using the below command:

docker logs [Container ID]

but getting the below error:

(node:5) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:5) UnhandledPromiseRejectionWarning: MongoError: command listDatabases requires authentication
    at Connection.<anonymous> (/node_modules/mongodb/lib/core/connection/pool.js:453:61)
    at Connection.emit (events.js:314:20)
    at processMessage (/node_modules/mongodb/lib/core/connection/connection.js:454:10)
    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connection.js:623:15)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:5) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Please note that this Container will be connecting to Mongo DB and all the details have been mentioned in the command. Looks like there is an update in the command which i'm not sure what. Below is what actually created the Mongo Express. It is showing as Running when i check with the dcoker ps command. However, when i type in a 'browser: localhost:8081' nothing is displayed.

Below is command that created Mongo Express:
docker run -d -p 8081:8081 -e ME_CONFIG_MONGODB_ADMINUSERNAME=admin -e ME_CONFIG_MONGODB_ADMINPASSWORD=password -e ME_CONFIG_MONGODB_SERVER=mongodb --name Mongo-express --net Mongo-Network mongo-express

**Comment by SAIMMINHAS** [comment]
Issue solved by myself.

**Comment by sivaraj-v** [comment]
Let us know the solution for this @SAIMMINHAS
