### ISSUE TITLE
This is totally rubbish!

### ISSUE THREAD

**Issue by mike-libra** [mongo-express/mongo-express-docker#83]
This is totally rubbish! The author is a retard! It's no use! The user name and password of database authentication are set, and the authentication is still required! Shit!

**Comment by mike-libra** [comment]
(node:8) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:8) UnhandledPromiseRejectionWarning: MongoError: command listDatabases requires authentication

**Comment by mike-libra** [comment]
It seems that the author's family died in a car accident! I haven't maintained the code for a long time!

**Comment by BlackthornYugen** [comment]
Abuse is not tolerated. I'm sorry you are dissatisfied with the development progress of this free and open source project. 

Keep in mind you and anyone else are free to submit pull requests or even make your own fork of the project.
