### ISSUE TITLE
Not able to run mongo-express image of docker

### ISSUE THREAD

**Issue by bobbyy16** [mongo-express/mongo-express-docker#89]
(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
developing-with-docker-mongo-express-1  | Could not connect to database using connectionString: mongodb://mongodb:27017/"

How to solve this error?

**Comment by luoxibo** [comment]
use the 0.54.

**Comment by bobbyy16** [comment]
Yeah, I've tried that as well

**Comment by anubhavgulati85** [comment]
I am facing the same issue as well on both latest and on 0.54 version.

**Comment by bobbyy16** [comment]
> I am facing the same issue as well on both latest and on 0.54 version.

There maybe some errors in your docker-compose.yaml file.
